### ISSUE TITLE
No weather and incorrect time

### ISSUE THREAD

**Issue by SavageAUS** [daledavies/jump#19]
I have set this up on unraid and no matter what i try i cannot get the time correct or the weather to show.
![Screen Shot 2022-03-20 at 11 41 33 am](https://user-images.githubusercontent.com/17326832/159143818-f717483d-cd9b-47d8-9cfe-1bb956697173.png)
![Screen Shot 2022-03-20 at 11 41 50 am](https://user-images.githubusercontent.com/17326832/159143822-88aa824f-f014-41a4-915d-e57c019c78ca.png)
![Screen Shot 2022-03-20 at 11 41 58 am](https://user-images.githubusercontent.com/17326832/159143824-dbdd0056-3172-43f6-8175-a9e34e4c48e7.png)
![Screen Shot 2022-03-20 at 11 42 14 am](https://user-images.githubusercontent.com/17326832/159143825-b2a8dbe9-c708-4bba-8cff-927c8ff0d56a.png)

EDIT: Weather is corrected by correcting the key spelling, please update dockerhub and github to correct this as you have different spelling for the key fields OWMAPIKEY & OWPAPIKEY should be OWMAPIKEY on both sites.

Time is still incorrect and goes to NaN:NaN

**Comment by quaintdev** [comment]
NaN issue was fixed in latest release. Are you on latest version?

**Comment by SavageAUS** [comment]
Yeah I am and to make sure I added the :latest tag. Either way the time is still incorrect.

**Comment by daledavies** [comment]
Could you try clearing your browser cache? Just in case you have an old version of the js bundle cached locally.

Also if this doesn't work could you post the json returned from weatherdata.php?

**Comment by SavageAUS** [comment]
As I stated previously the weather is not fine once I corrected the mismatch info from GitHub and docker hub to the correct key. It is just the time that is incorrect. I will clear browser cache once server is back online (getting renovations done)

**Comment by daledavies** [comment]
Please post the output from weatherdata.php as that would be useful for me to investigate potential problems with the time, the timezone returned from open weather via this endpoint is used to calculate the display time and the json returned from this endpoint can be used to help me recreate your issue. Thanks for your help, o hope your renovations aren't too disruptive.

**Comment by SavageAUS** [comment]
We are getting a wall removed so we have had to clear out for a few days. As soon as I'm back home and server online I'll send what ever you need. I might even sneak in the house tonight and power up lol.

**Comment by SavageAUS** [comment]
I have fired up my server and in my appdata folder i cannot find weatherdata.php. Did i forget to map a folder?

**Comment by SavageAUS** [comment]
I must have had a brain fart.
Here is the contents of weatherdata.php.
`/var/www/html/api # cat weatherdata.php 
<?php
/**
 * Proxy requests to OpenWeather API and cache response.
 *
 * @author Dale Davies <dale@daledavies.co.uk>
 * @license MIT
 */

// Provided by composer for psr-4 style autoloading.
require __DIR__ .'/../vendor/autoload.php';

$config = new Jump\Config();
$cache = new Jump\Cache($config);

$owmapiurlbase = 'https://api.openweathermap.org/data/2.5/weather';
$units = $config->parse_bool($config->get('metrictemp')) ? 'metric' : 'imperial';

// If we have either lat or lon query params then cast them to a float, if not then
// set the values to zero.
$lat = isset($_GET['lat']) ? (float) $_GET['lat'] : 0;
$lon = isset($_GET['lon']) ? (float) $_GET['lon'] : 0;

// Use the lat and lon values provided unless they are zero, this might mean that
// either they werent provided as query params or they couldn't be cast to a float.
// If they are zero then use the default latlong from config.
$latlong = [$lat, $lon];
if ($lat === 0 || $lon === 0) {
    $latlong = explode(',', $config->get('latlong', false));
}

// This is the API endpoint and params we are using for the query,
$url =  $owmapiurlbase
        .'?units=' . $units
        .'&lat=' . $latlong[0]
        .'&lon=' . $latlong[1]
        .'&appid=' . $config->get('owmapikey', false);

// Use the cache to store/retrieve data, make an md5 hash of latlong so it is not possible
// to track location history form the stored cache.
$weatherdata = $cache->load(cachename: 'weatherdata', key: md5(json_encode($latlong)), callback: function() use ($url) {
    // Ask the API for some data.
    $ch = curl_init();
    curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
    curl_setopt($ch, CURLOPT_URL, $url);
    curl_setopt($ch, CURLOPT_FOLLOWLOCATION, 1);
    curl_setopt($ch, CURLOPT_FAILONERROR, true);
    $response = curl_exec($ch);

    // Just in case something went wrong with the request we'll capture the error.
    if (curl_errno($ch)) {
        $curlerror = curl_error($ch);
    }
    curl_close($ch);
    // If we had an error then return the error message and exit, otherwise return the API response.
    if (isset($curlerror)) {
        die($curlerror);
    }
    return $response;
});

// We made it here so output the API response as json.
header('Content-Type: application/json; charset=utf-8');
echo $weatherdata;/var/www/html/api # `

**Comment by SavageAUS** [comment]
Ok disregard all of the above.
Even with using the :latest tag it took a few days for the latest update to come through.
Unraid just told me that an update for Jump was available - updated and all is correct now.
![Screenshot_20220322_223117](https://user-images.githubusercontent.com/17326832/159477453-1d8135c6-fcd4-4877-a7a8-f465705fd7e1.png)
Now to customise :)
