### ISSUE TITLE
(Status: error) for site behind Authelia

### ISSUE THREAD

**Issue by cinderblockgames** [daledavies/jump#68]
Does the site redirecting for authentication keep jump from being able to pick up that the site is up?  I feel like 2XX and 3XX should be considered up, 4XX and 5XX considered down.  (Or maybe have the ability to specify which status codes are considered up?)

**Comment by cinderblockgames** [comment]
Looks like this is because the HEAD method is returning a 405 Method Not Allowed.

**Comment by daledavies** [comment]
Yep essentially 4xx or 5xx HTTP response codes are considered down, as per the underlying guzzle library. When I am able I do plan on adding some more options to the status checking feature, maybe an alternate URL or as you suggest a list of acceptable responses.

Thanks for reaching out, keep me posted on the response from authelia 😀

**Comment by cinderblockgames** [comment]
@daledavies Seems like the easiest approach (for here anyway) would be a way to override the request type per site.  So, something like
```
        {
            "name": "Recipes",
            "url": "https://recipes.example.com",
            "description": "Recipes and meal planning",
            "icon": "tandoor.svg",
            "verb": "GET"
        }
```

**Comment by cinderblockgames** [comment]
@daledavies Don't suppose you want to add to the [discussion](https://github.com/authelia/authelia/discussions/4998)?

**Comment by cinderblockgames** [comment]
Based on the discussion, it sounds like maybe the best thing to do is to allow the list of acceptable responses while also allowing a specification of if redirects should be followed?  From my viewpoint, if the site is returning a 303 See Other, it's up for my use case.

**Comment by daledavies** [comment]
Yes this feature was only intended to be a simple status check, I'm not going to implement authentication and passing a request body etc.

I'm happy to implement additional request methods and a list of acceptable response codes if I can though.

One other thing though, I had set the gizzle client options to allow redirects, so this shouldn't be a problem.

**Comment by daledavies** [comment]
Aside from this, would an alternate status URL help too? I think it might be beneficial for some cases.

**Comment by cinderblockgames** [comment]
@daledavies I do think that would help - being able to point to one place for the link and another for the status could let me try to set up a health check endpoint that's not protected by authentication.

**Comment by daledavies** [comment]
I'll see about implementing all the above then :)

**Comment by daledavies** [comment]
This will probably help with https://github.com/daledavies/jump/issues/53

**Comment by daledavies** [comment]
I've added a change to allow for per-site status options as discussed above. I'll push a new release of Jump soon but just want to look at a few other issues first.

**Comment by cinderblockgames** [comment]
@daledavies Trying to test this - I added `"request_method": "GET"` to the sites.json config for this site, but I'm still getting an error.  Are there logs that I can check to see what's happening?  If I curl directly with GET, I do get a 200 OK back, so not sure what's going on.

**Comment by daledavies** [comment]
There aren't any verbose logs specific to the status checking, you'll get a mixture of nginx and php logs via `docker logs`. I can make it give us more logs though, I'll hack something into a test image tomorrow if I can to give us an idea of the response jump is getting.

Other than that remember docker has its own internal network so the true test would be to exec into the jump container and curl from there, if you haven't already.

**Comment by cinderblockgames** [comment]
Relevant bits:

```
/var/www/html # curl -v "https://recipes.example.com/invite/[redacted]"
```
```
< HTTP/1.1 302 Found
<a href="https://login.example.com/?rd=https%3A%2F%2Frecipes.example.com%2Finvite%2F[redacted]&amp;rm=GET">302 Found</a>
```
```
/var/www/html # curl -v "https://login.example.com/?rd=https%3A%2F%2Frecipes
.example.com%2Finvite%2F[redacted]&amp;rm=GET"
```
```
< HTTP/1.1 200 OK
```

**Comment by daledavies** [comment]
All my testing suggests that Jump correctly sends a GET request and also follows redirects, the status returned is from the final destination. I think though that by default guzzle will only follow 5 redirects so that could possibly be your problem.

Could you test with curl like before, but also paste the location header rather than the response body?

**Comment by daledavies** [comment]
It might also help if I set guzzle to add the referrer when redirecting, by default it does not and this works for everything I've tested with, but maybe authelia needs it.

**Comment by daledavies** [comment]
While testing with curl you could also tell it to follow redirects and limit the number to 5, will make it similar to what guzzle is joing in Jump...

`curl -vL --max-redirs 5 "https://recipes.example.com/invite/[redacted]"`

**Comment by daledavies** [comment]
I've pushed an image to Docker Hub you can test with, it shold give some more information in `docker logs`. Specifically the eventual status code, the redirect history and the status code at each redirect.

Could you pull daledavies/jump:redirecttest and give it a spin? :)

**Comment by cinderblockgames** [comment]
That's working!
Still don't know why the app is seeing just a straight 401 instead of the 302, but I'm happy.  Thank you!

**Comment by daledavies** [comment]
Interesting, glad it's working for you. Out of interest can you share your full sites.json file? That first error is unrelated to this problem but I'm intrigued what caused it.

**Comment by cinderblockgames** [comment]
```
{
  "sites": [
    {
      "name": "Home",
      "url" : "https://welcometo.example.com",
      "description": "You are here",
      "icon": "jump.png"
    },
    {
       "name": "Media",
       "url" : "https://media.example.com",
       "description": "Watch media",
       "icon": "jellyfin.png"
    },
    {
       "name": "Requests",
       "url" : "https://requests.media.example.com",
       "description": "Request series and movies",
       "icon": "jellyseerr.svg"
    },
    {
       "name": "Recipes",
       "url": "https://recipes.example.com/invite/[redacted]",
       "description": "Recipes and meal planning",
       "icon": "tandoor.svg",
       "status": {
         "allowed_status_codes": [401]
        }
    },
    {
       "name": "Restaurants",
       "url" : "https://wiki.example.com/example/restaurants",
       "description": "Example  restaurant ratings",
       "icon": "wikijs.svg"
    },
    {
       "name": "Reset Password",
       "url" : "https://login.example.com/reset-password/step1",
       "description": "Reset your password",
       "icon": "authelia.jpg"
    }
  ]
}
```

**Comment by daledavies** [comment]
> So the app is seeing a 401 instead of the 302. Trying with `"allowed_status_codes": [401]"` instead.

Perhaps a 401 might be correct, in terms of the request being unauthorized.

Also some differences between the curl and what Jump is doing, Curl wil be using the GET method where your configuration for Jump means it will use the default HEAD method for the request. 

It looks like Authelia have implemented something to handle HEAD requests, but maybe they might respond differently depending on the request method.

**Comment by cinderblockgames** [comment]
If I do it with a HEAD request, I get:

```
HTTP/1.1 303 See Other
HTTP/1.1 405 Method Not Allowed
```

So still don't really know where the 401 comes from.

**Comment by daledavies** [comment]
> ```
> NOTICE: PHP message: Site (https://recipes.example.com/invite/[redacted]) returned status of... 401
> 2023/03/07 16:26:00 [error] 30#30: *17 FastCGI sent in stderr: "PHP message: Site (https://recipes.example.com/invite/[redacted]) returned status of... 401" while reading response header from upstream, client: 10.0.1.87, server: _, request: "GET /api/status/94b68d17fb7a292d5c0f130303a0fd16fe363ef78f0e3ae1ef1456bf827d418e/ HTTP/1.1", upstream: "fastcgi://unix:/run/php-fpm.sock:", host: "welcometo.lab.example.com", referrer: "https://welcometo.example.com/"
> ```

If you we're not seeing anything in Jump's logs referring to `redirect  history` or `redirect status history` then this suggests Authelia isn't responding with a redirect status at all, it's just straight up responding with a 401 Unauthorized code.

I'm trying to think why this might be. I've done some testing with guzzle in Jump and can see there are two differences in the request headers sent by Jump are that guzzle doesn't set the `Accept: */*` header like curl and it uses a user agent of `"GuzzleHttp/7"` compared to curl's `curl/7.81.0`.

Anyway I can't help thinking that we might gain some insight from Authelia's own logs, can you see anything relevant in those when you do the curl vs Jump test?

**Comment by daledavies** [comment]
@cinderblockgames Did you find anything in the Authelia logs?

**Comment by cinderblockgames** [comment]
I haven't had a chance, but I'll try to look this week.
